[server]

headless = true
port = 8501
enableCORS = false


[theme]

primaryColor="#154c79" 
backgroundColor="black" 
secondaryBackgroundColor="black"
codeBackgroundColor = "black"
textColor="#fff"
font="sans serif"
